name: dl

on:
  repository_dispatch:
    types: dl
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * *

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 3
        keep_minimum_runs: 0
    - name: 企业微信推送
      if: always()
      run: curl -H "Content-Type:application/json" -X POST -d '{"touser":"@all","msgtype":"text","agentid":"${{ secrets.aid }}","text":{"content":"Actions-云编译\nop清理成功"}}' https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=${{ secrets.token }}
