name: dl

on:
  repository_dispatch:
    types: dl
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * *

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 3
        keep_minimum_runs: 0
    - name: pushbot推送
      if: always()
      run: curl -H "Content-Type:application/json" -X POST -d '{"token":"${{ secrets.pushbot }}","title":"op清理成功","content":"op清理成功结束","template":"json"}' http://www.pushplus.plus/send
